# Cómo trabajar con Matrices

In [1]:
import tensorflow as tf
session = tf.Session()


## 1. Cómo crear matrices

In [19]:
identity = tf.diag([1.,1.,1.,1.])
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
A = tf.truncated_normal([3,4])
print(session.run(A))

[[-0.36151385  0.26288822  0.82057774  0.58631545]
 [ 0.02149232  0.03546572  0.7458191   1.7819456 ]
 [ 0.17085026  1.1022977  -0.7611906  -0.03098968]]


In [14]:
B = tf.fill([3,4],1988.)
print(session.run(B))

[[1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]]


In [12]:
C = tf.random_uniform([4,3])
print(session.run(C))

[[0.06782281 0.91193044 0.06708479]
 [0.44713628 0.6037891  0.60076594]
 [0.25298274 0.63227534 0.5795405 ]
 [0.94033754 0.4446528  0.29243302]]


In [13]:
import numpy as np
data = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices

In [15]:
print(session.run(A+B))

[[1989.9607 1987.359  1987.1428 1987.1112]
 [1987.7938 1987.4471 1988.4878 1988.4991]
 [1987.417  1988.6324 1987.5516 1986.9205]]


In [17]:
print(session.run(tf.matmul(A,C)))

[[ 1.3347223   1.9526694   1.8022423 ]
 [-0.53489435 -0.04331152  0.09541965]
 [-1.0320356  -0.9476245  -0.05275306]]


In [20]:
print(session.run(tf.matmul(A,identity)))

[[ 3.2231078e-01 -3.4820005e-01  4.7915968e-01 -9.1175157e-01]
 [-7.5466323e-01 -1.7581029e+00  3.5113543e-01 -5.7520008e-01]
 [-3.7075675e-01  1.8686314e-04 -7.3617905e-01  6.9339144e-01]]


## 3. Transpuesta y determinante, inversa

In [21]:
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [22]:
print(session.run(tf.matrix_determinant(D)))

6.66133814775094e-16


In [24]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.],[-3.,-6.,1.],[6.,5.,4.]]))
print(session.run(tf.matrix_determinant(E)))

70.00000000000003


In [29]:
Einv =tf.matrix_inverse(E)
print(session.run(Einv))

[[-4.14285714e-01  1.00000000e-01  2.85714286e-01]
 [ 2.57142857e-01 -2.00000000e-01 -1.42857143e-01]
 [ 3.00000000e-01  1.00000000e-01  8.32667268e-18]]


In [30]:
print(session.run(tf.matmul(E,Einv)))

[[ 1.00000000e+00  2.77555756e-17  2.49800181e-17]
 [ 1.66533454e-16  1.00000000e+00  8.32667268e-18]
 [-2.22044605e-16  0.00000000e+00  1.00000000e+00]]


## 4. Descomposición

In [31]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Valores y vectores propios

In [32]:
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.54474316   0.51459454   9.03014862]


In [33]:
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.54474316,   0.51459454,   9.03014862]), array([[-0.43573042, -0.71173038,  0.55097992],
       [-0.78060869,  0.60357012,  0.16233666],
       [ 0.44809495,  0.35936469,  0.81857677]]))
