# Operaciones con TensorFlow

In [ ]:
import tensorflow as tf
session = tf.Session()

## Operaciones aritmeticas

In [ ]:
x = 3
y = 4

In [ ]:
print(session.run(tf.add(x , y)))

In [ ]:
print(session.run(tf.subtract(x,y)))

In [ ]:
print(session.run(tf.multiply(x,y)))

In [ ]:
print(session.run(tf.div(x,y)))

In [ ]:
print(session.run(tf.truediv(x,y)))

In [ ]:
print(session.run(tf.floordiv(x,y)))

In [ ]:
print(session.run(tf.floordiv(y,x)))

In [ ]:
print(session.run(tf.mod(x,y)))

In [ ]:
print(session.run(tf.mod(y,x)))

In [18]:
print(session.run(tf.cross([1.,0.,0.],[0.,5.,2.])))

[ 0. -2.  5.]


## Funciones matemáticas

In [19]:
x = [-3.,-2.,-1,0.,1.,2.]
print(session.run(tf.abs(x)))

[3. 2. 1. 0. 1. 2.]


In [20]:
print(session.run(tf.ceil(6.4)))

7.0


In [21]:
print(session.run(tf.floor(6.4)))

6.0


In [22]:
print(session.run(tf.round(6.4)))

6.0


In [23]:
print(session.run(tf.sin(x)))

[-0.14112    -0.9092974  -0.84147096  0.          0.84147096  0.9092974 ]


In [24]:
print(session.run(tf.cos(x)))

[-0.9899925  -0.4161468   0.5403023   1.          0.5403023  -0.41614684]


In [25]:
print(session.run(tf.tan(x)))

[ 0.14254653  2.18504    -1.5574079   0.          1.5574077  -2.1850398 ]


In [26]:
print(session.run(tf.exp(x)))

[0.04978707 0.13533528 0.36787945 1.         2.7182817  7.389056  ]


In [27]:
print(session.run(tf.log(x)))

[      nan       nan       nan      -inf 0.        0.6931472]


In [28]:
y = [4.,2.,-1,0.,1.,2.]


In [29]:
print(session.run(tf.maximum(x,y)))

[ 4.  2. -1.  0.  1.  2.]


In [30]:
print(session.run(tf.minimum(x,y)))

[-3. -2. -1.  0.  1.  2.]


In [34]:
print(session.run(tf.negative(x)))

[ 3.  2.  1. -0. -1. -2.]


In [40]:
print(session.run(tf.pow(x,y)))

[81.  4. -1.  1.  1.  4.]


In [36]:
print(session.run(tf.pow(y,x)))

[ 0.015625  0.25     -1.        1.        1.        4.      ]


In [37]:
print(session.run(tf.sqrt(x)))

[      nan       nan       nan 0.        1.        1.4142135]


In [38]:
print(session.run(tf.sqrt(y)))

[1.9999999 1.4142134       nan 0.        1.        1.4142135]


In [39]:
print(session.run(tf.square(x)))

[9. 4. 1. 0. 1. 4.]


In [41]:
print(session.run(tf.sign(x)))

[-1. -1. -1.  0.  1.  1.]


## Otras Funciones

In [43]:
print(session.run(tf.digamma(x)))

[       inf        inf        inf        inf -0.5772159  0.4227842]


In [44]:
print(session.run(tf.lbeta(x)))

nan


In [45]:
print(session.run(tf.lgamma(x)))

[inf inf inf inf  0.  0.]


In [46]:
print(session.run(tf.erf(x)))

[-0.9999779  -0.9953223  -0.84270084  0.          0.84270084  0.9953223 ]


In [47]:
print(session.run(tf.erfc(x)))

[1.9999778  1.9953222  1.8427008  1.         0.1572992  0.00467773]


In [49]:
print(session.run(tf.squared_difference(x,y)))

[49. 16.  0.  0.  0.  0.]


In [54]:
print(session.run(tf.tan(3.1415/4.)))

0.9999537


## Funciones Propias

$$ y = 5x^2 -7x + 15 $$

In [58]:
def custom_parabola(value):
    return tf.subtract(5*tf.square(value),7*value)+ 15

In [59]:
print(session.run(custom_parabola(5)))

105
