## Dividiendo la ejecución en capas


In [1]:
import tensorflow as tf
session = tf.Session()

- $X \in \mathbb R_{3\times4} $

In [5]:
import numpy as np
my_array = np.array([[1.,3.,5.,7.],
                    [-2.,0.,7.,6.],
                    [-6.,-1.,0.,3.]])

In [6]:
x_vals = np.array([my_array, my_array+1])
x_vals

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [7]:
x_data = tf.placeholder(tf.float32, shape=(3,4))

- $m_1 \in \mathbb R^4$
- $m_2 , a1 \in \mathbb R$

### m1 es vector columna (ver la definición)
### Hay que recordar que son tensores: 
- Una constante es un tensor de orden 0
- vector es un tensor de orden 1
- matriz y formas cuadráticas son tensores de order 2

In [10]:
m1 = tf.constant([[1.],[0.],[-2.],[5.]])
m2 = tf.constant([[7.]])
a1 = tf.constant([[15.]])

## Operaciones
$$ (X\cdot m_1)m_2 + a_1 $$

In [11]:
prod1 = tf.matmul(x_data,m1)
prod2 = tf.matmul(prod1,m2)
add1 = tf.add(prod2, a1)

In [13]:
for x_val in x_vals:
    print(session.run(add1,feed_dict={x_data: x_val}))

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]
